//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace pwiz.Skyline.Model.Lists.Panorama.GeneratedCode {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://labkey.org/list/xml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://labkey.org/list/xml", IsNullable=false)]
    public partial class lists {
        
        private listsList[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("list")]
        public listsList[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://labkey.org/list/xml")]
    public partial class listsList {
        
        private string nameField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int discussionsField;
        
        private bool allowDeleteField;
        
        private bool allowUploadField;
        
        private bool allowExportField;
        
        private bool eachItemIndexField;
        
        private int eachItemTitleSettingField;
        
        private string eachItemTitleTemplateField;
        
        private int eachItemBodySettingField;
        
        private string eachItemBodyTemplateField;
        
        private bool entireListIndexField;
        
        private int entireListIndexSettingField;
        
        private int entireListTitleSettingField;
        
        private string entireListTitleTemplateField;
        
        private int entireListBodySettingField;
        
        private string entireListBodyTemplateField;
        
        private bool fileAttachmentIndexField;
        
        public listsList() {
            this.discussionsField = 0;
            this.allowDeleteField = true;
            this.allowUploadField = true;
            this.allowExportField = true;
            this.eachItemIndexField = false;
            this.eachItemTitleSettingField = 0;
            this.eachItemBodySettingField = 0;
            this.entireListIndexField = false;
            this.entireListIndexSettingField = 0;
            this.entireListTitleSettingField = 0;
            this.entireListBodySettingField = 0;
            this.fileAttachmentIndexField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int discussions {
            get {
                return this.discussionsField;
            }
            set {
                this.discussionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool allowDelete {
            get {
                return this.allowDeleteField;
            }
            set {
                this.allowDeleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool allowUpload {
            get {
                return this.allowUploadField;
            }
            set {
                this.allowUploadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool allowExport {
            get {
                return this.allowExportField;
            }
            set {
                this.allowExportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool eachItemIndex {
            get {
                return this.eachItemIndexField;
            }
            set {
                this.eachItemIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int eachItemTitleSetting {
            get {
                return this.eachItemTitleSettingField;
            }
            set {
                this.eachItemTitleSettingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string eachItemTitleTemplate {
            get {
                return this.eachItemTitleTemplateField;
            }
            set {
                this.eachItemTitleTemplateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int eachItemBodySetting {
            get {
                return this.eachItemBodySettingField;
            }
            set {
                this.eachItemBodySettingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string eachItemBodyTemplate {
            get {
                return this.eachItemBodyTemplateField;
            }
            set {
                this.eachItemBodyTemplateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool entireListIndex {
            get {
                return this.entireListIndexField;
            }
            set {
                this.entireListIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int entireListIndexSetting {
            get {
                return this.entireListIndexSettingField;
            }
            set {
                this.entireListIndexSettingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int entireListTitleSetting {
            get {
                return this.entireListTitleSettingField;
            }
            set {
                this.entireListTitleSettingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string entireListTitleTemplate {
            get {
                return this.entireListTitleTemplateField;
            }
            set {
                this.entireListTitleTemplateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int entireListBodySetting {
            get {
                return this.entireListBodySettingField;
            }
            set {
                this.entireListBodySettingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string entireListBodyTemplate {
            get {
                return this.entireListBodyTemplateField;
            }
            set {
                this.entireListBodyTemplateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool fileAttachmentIndex {
            get {
                return this.fileAttachmentIndexField;
            }
            set {
                this.fileAttachmentIndexField = value;
            }
        }
    }
}
